[tool.poetry]
name = "assignment-frontend-engineer"
version = "0.1.0"
description = ""
authors = ["Ambar Das <ambar@source.ag>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
